-- 코드를 입력하세요
-- 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고
-- 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차에 대해서 
-- 대여 금액을 기준으로 내림차순, 자동차 종류를 기준으로 오름차순 자동차 ID 내림차순
SELECT c.CAR_ID, c.CAR_TYPE, ROUND(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR as c
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as h
ON c.CAR_ID = h.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN as P
ON c.CAR_TYPE = p.CAR_TYPE
WHERE c.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01'
) AND P.DURATION_TYPE='30일 이상'
GROUP BY CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000 AND c.CAR_TYPE IN ('세단', 'SUV')
ORDER BY FEE DESC, c.CAR_TYPE ASC, CAR_ID ASC;
