-- 코드를 작성해주세요
WITH RECURSIVE GENERATIONS AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT e.ID, e.PARENT_ID, (g.GENERATION + 1) AS GENERATION
    FROM ECOLI_DATA AS e
    JOIN GENERATIONS AS g
    ON e.PARENT_ID = g.ID
)
SELECT COUNT(GENERATION) AS COUNT, GENERATION
FROM GENERATIONS
WHERE NOT ID IN (SELECT DISTINCT PARENT_ID
                FROM ECOLI_DATA
                WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION ASC
