-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD AS b
JOIN USED_GOODS_USER as u
ON b.WRITER_ID = u.USER_ID
WHERE STATUS = "DONE"
GROUP BY b.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;
